#!/usr/bin/env python3
"""Plan a Caddy edge cutover between frontend colors. Does not start containers."""

from __future__ import annotations

import argparse
import sys

COLORS = ("blue", "green")


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(2)


def other(color: str) -> str:
    if color not in COLORS:
        fail("color 只能是 blue 或 green")
    return "green" if color == "blue" else "blue"


def upstream(color: str) -> str:
    if color == "live":
        target = "frontend:8080"
    else:
        other(color)
        target = f"frontend-{color}:8080"
    return f"reverse_proxy {target}\n"


def edge_compose(color: str, registry: str, tag: str) -> str:
    other(color)
    registry = registry.rstrip("/")
    image = f"{registry}/frontend:{tag}"
    return f"""# generated by scripts/bluegreen.py
services:
  frontend-{color}:
    image: {image}
    container_name: skytrace-frontend-{color}
    restart: unless-stopped
    environment:
      NGINX_SERVER_NAME: ${{SKYTRACE_DOMAIN:-localhost}}
      KEYCLOAK_PUBLIC_URL: https://${{SKYTRACE_DOMAIN}}
      KEYCLOAK_REALM: skytrace
      KEYCLOAK_CLIENT_ID: skytrace-web
      MINIO_EVIDENCE_BUCKET: ${{MINIO_EVIDENCE_BUCKET:-skytrace-evidence}}
    ports:
      - "127.0.0.1:${{FRONTEND_COLOR_PORT:-8898}}:8080"
    networks:
      edge:
        aliases:
          - frontend-{color}
      backend: {{}}
networks:
  edge:
    external: true
    name: skytrace-edge
  backend:
    external: true
    name: skytrace-backend
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    nxt = sub.add_parser("next")
    nxt.add_argument("--color", required=True)
    up = sub.add_parser("upstream")
    up.add_argument("--color", required=True)
    stack = sub.add_parser("stack")
    stack.add_argument("--color", required=True)
    stack.add_argument("--registry", required=True)
    stack.add_argument("--tag", required=True)
    args = parser.parse_args()
    if args.command == "next":
        print(other(args.color))
        return
    if args.command == "upstream":
        sys.stdout.write(upstream(args.color))
        return
    sys.stdout.write(edge_compose(args.color, args.registry, args.tag))


if __name__ == "__main__":
    main()
