#!/usr/bin/env python3
"""Build/validate SkyTrace release image digest manifests and compose overlays."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

SERVICES = (
    "backend-ai",
    "backend-java",
    "backend-node",
    "gateway",
    "frontend",
    "admin-service",
    "admin-frontend",
)

TAG_RE = re.compile(r"^main-[0-9a-f]{7,40}$")
DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
DIGEST_FIND_RE = re.compile(r"sha256:[0-9a-f]{64}")


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(2)


def load_manifest(path: Path) -> dict[str, Any]:
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"无法读取 manifest {path}: {exc}")
    if not isinstance(doc, dict):
        fail(f"{path} 不是 JSON object")
    return doc


def validate_manifest(doc: dict[str, Any], expect_tag: str | None = None) -> dict[str, Any]:
    tag = doc.get("tag")
    if not isinstance(tag, str) or not TAG_RE.fullmatch(tag):
        fail("manifest.tag 必须是 main-<git-sha>")
    if expect_tag is not None and tag != expect_tag:
        fail(f"manifest.tag={tag} 与 IMAGE_TAG={expect_tag} 不一致")
    images = doc.get("images")
    if not isinstance(images, dict):
        fail("manifest.images 必须是 object")
    missing = [name for name in SERVICES if name not in images]
    extra = [name for name in images if name not in SERVICES]
    if missing or extra:
        fail(f"manifest.images 服务集合不对 missing={missing} extra={extra}")
    for name in SERVICES:
        digest = images[name]
        if not isinstance(digest, str) or not DIGEST_RE.fullmatch(digest):
            fail(f"manifest.images.{name} 必须是 sha256:<64 hex>，实际：{digest!r}")
    return doc


def overlay_text(registry: str, images: dict[str, str]) -> str:
    registry = registry.rstrip("/")
    lines = ["# generated by scripts/release_manifest.py; do not edit", "services:"]
    for name in SERVICES:
        lines.append(f"  {name}:")
        lines.append(f"    image: {registry}/{name}@{images[name]}")
    return "\n".join(lines) + "\n"


def inspect_digest(reference: str) -> str:
    result = subprocess.run(
        ["docker", "buildx", "imagetools", "inspect", reference],
        capture_output=True,
        text=True,
        check=False,
    )
    blob = (result.stdout or "") + "\n" + (result.stderr or "")
    match = DIGEST_FIND_RE.search(blob)
    if result.returncode != 0 or match is None:
        fail(f"无法解析 digest：{reference}\n{blob}")
    return match.group(0)


def cmd_validate(args: argparse.Namespace) -> None:
    validate_manifest(load_manifest(Path(args.manifest)), args.expect_tag)
    print("release manifest 校验通过")


def cmd_overlay(args: argparse.Namespace) -> None:
    doc = validate_manifest(load_manifest(Path(args.manifest)), args.expect_tag)
    Path(args.output).write_text(
        overlay_text(args.registry, doc["images"]),
        encoding="utf-8",
    )


def cmd_inspect(args: argparse.Namespace) -> None:
    if not TAG_RE.fullmatch(args.tag):
        fail("IMAGE_TAG must be immutable main-<git-sha>")
    registry = args.registry.rstrip("/")
    images = {
        name: inspect_digest(f"{registry}/{name}:{args.tag}")
        for name in SERVICES
    }
    doc = {"tag": args.tag, "images": images}
    validate_manifest(doc, args.tag)
    Path(args.output).write_text(
        json.dumps(doc, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    validate = sub.add_parser("validate")
    validate.add_argument("--manifest", required=True)
    validate.add_argument("--expect-tag")
    validate.set_defaults(func=cmd_validate)

    overlay = sub.add_parser("overlay")
    overlay.add_argument("--registry", required=True)
    overlay.add_argument("--manifest", required=True)
    overlay.add_argument("--output", required=True)
    overlay.add_argument("--expect-tag")
    overlay.set_defaults(func=cmd_overlay)

    inspect = sub.add_parser("inspect")
    inspect.add_argument("--registry", required=True)
    inspect.add_argument("--tag", required=True)
    inspect.add_argument("--output", required=True)
    inspect.set_defaults(func=cmd_inspect)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
